/* warning
the move generation functions make a lot of assumptions, so custom boards with positions unreachable
in regular chess games may create bugs (ie pawns on promotion squares, opposite kings touching, etc.)
*/

#define USE_REGULAR_BOARD 1

#if USE_REGULAR_BOARD
const char startingBoard[64] = {
    blackRook, blackKnight, blackBishop, blackQueen, blackKing, blackBishop, blackKnight, blackRook,
    blackPawn, blackPawn,   blackPawn,   blackPawn,  blackPawn, blackPawn,   blackPawn,   blackPawn,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    whitePawn, whitePawn,   whitePawn,   whitePawn,  whitePawn, whitePawn,   whitePawn,   whitePawn,
    whiteRook, whiteKnight, whiteBishop, whiteQueen, whiteKing, whiteBishop, whiteKnight, whiteRook
};
#else
const char startingBoard[64] = {
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     whiteKing,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     blackKing,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
};
#endif


// data generated by move_maker.py

// precomputed bitboards for checks
// bitmasks for: rook moves, bishop moves, knight moves, king moves, white pawn moves, black pawn moves
const uint64_t pos0[6] = {0x1010101010101fe, 0x8040201008040200, 0x20400, 0x302, 0x0, 0x200};
const uint64_t pos1[6] = {0x2020202020202fd, 0x80402010080500, 0x50800, 0x705, 0x0, 0x500};
const uint64_t pos2[6] = {0x4040404040404fb, 0x804020110a00, 0xa1100, 0xe0a, 0x0, 0xa00};
const uint64_t pos3[6] = {0x8080808080808f7, 0x8041221400, 0x142200, 0x1c14, 0x0, 0x1400};
const uint64_t pos4[6] = {0x10101010101010ef, 0x182442800, 0x284400, 0x3828, 0x0, 0x2800};
const uint64_t pos5[6] = {0x20202020202020df, 0x10204885000, 0x508800, 0x7050, 0x0, 0x5000};
const uint64_t pos6[6] = {0x40404040404040bf, 0x102040810a000, 0xa01000, 0xe0a0, 0x0, 0xa000};
const uint64_t pos7[6] = {0x808080808080807f, 0x102040810204000, 0x402000, 0xc040, 0x0, 0x4000};
const uint64_t pos8[6] = {0x10101010101fe01, 0x4020100804020002, 0x2040004, 0x30203, 0x0, 0x20000};
const uint64_t pos9[6] = {0x20202020202fd02, 0x8040201008050005, 0x5080008, 0x70507, 0x0, 0x50000};
const uint64_t pos10[6] = {0x40404040404fb04, 0x804020110a000a, 0xa110011, 0xe0a0e, 0x0, 0xa0000};
const uint64_t pos11[6] = {0x80808080808f708, 0x804122140014, 0x14220022, 0x1c141c, 0x0, 0x140000};
const uint64_t pos12[6] = {0x101010101010ef10, 0x18244280028, 0x28440044, 0x382838, 0x0, 0x280000};
const uint64_t pos13[6] = {0x202020202020df20, 0x1020488500050, 0x50880088, 0x705070, 0x0, 0x500000};
const uint64_t pos14[6] = {0x404040404040bf40, 0x102040810a000a0, 0xa0100010, 0xe0a0e0, 0x0, 0xa00000};
const uint64_t pos15[6] = {0x8080808080807f80, 0x204081020400040, 0x40200020, 0xc040c0, 0x0, 0x400000};
const uint64_t pos16[6] = {0x101010101fe0101, 0x2010080402000204, 0x204000402, 0x3020300, 0x0, 0x2000000};
const uint64_t pos17[6] = {0x202020202fd0202, 0x4020100805000508, 0x508000805, 0x7050700, 0x500, 0x5000000};
const uint64_t pos18[6] = {0x404040404fb0404, 0x804020110a000a11, 0xa1100110a, 0xe0a0e00, 0xa00, 0xa000000};
const uint64_t pos19[6] = {0x808080808f70808, 0x80412214001422, 0x1422002214, 0x1c141c00, 0x1400, 0x14000000};
const uint64_t pos20[6] = {0x1010101010ef1010, 0x1824428002844, 0x2844004428, 0x38283800, 0x2800, 0x28000000};
const uint64_t pos21[6] = {0x2020202020df2020, 0x102048850005088, 0x5088008850, 0x70507000, 0x5000, 0x50000000};
const uint64_t pos22[6] = {0x4040404040bf4040, 0x2040810a000a010, 0xa0100010a0, 0xe0a0e000, 0xa000, 0xa0000000};
const uint64_t pos23[6] = {0x80808080807f8080, 0x408102040004020, 0x4020002040, 0xc040c000, 0x4000, 0x40000000};
const uint64_t pos24[6] = {0x1010101fe010101, 0x1008040200020408, 0x20400040200, 0x302030000, 0x20000, 0x200000000};
const uint64_t pos25[6] = {0x2020202fd020202, 0x2010080500050810, 0x50800080500, 0x705070000, 0x50000, 0x500000000};
const uint64_t pos26[6] = {0x4040404fb040404, 0x4020110a000a1120, 0xa1100110a00, 0xe0a0e0000, 0xa0000, 0xa00000000};
const uint64_t pos27[6] = {0x8080808f7080808, 0x8041221400142241, 0x142200221400, 0x1c141c0000, 0x140000, 0x1400000000};
const uint64_t pos28[6] = {0x10101010ef101010, 0x182442800284482, 0x284400442800, 0x3828380000, 0x280000, 0x2800000000};
const uint64_t pos29[6] = {0x20202020df202020, 0x204885000508804, 0x508800885000, 0x7050700000, 0x500000, 0x5000000000};
const uint64_t pos30[6] = {0x40404040bf404040, 0x40810a000a01008, 0xa0100010a000, 0xe0a0e00000, 0xa00000, 0xa000000000};
const uint64_t pos31[6] = {0x808080807f808080, 0x810204000402010, 0x402000204000, 0xc040c00000, 0x400000, 0x4000000000};
const uint64_t pos32[6] = {0x10101fe01010101, 0x804020002040810, 0x2040004020000, 0x30203000000, 0x2000000, 0x20000000000};
const uint64_t pos33[6] = {0x20202fd02020202, 0x1008050005081020, 0x5080008050000, 0x70507000000, 0x5000000, 0x50000000000};
const uint64_t pos34[6] = {0x40404fb04040404, 0x20110a000a112040, 0xa1100110a0000, 0xe0a0e000000, 0xa000000, 0xa0000000000};
const uint64_t pos35[6] = {0x80808f708080808, 0x4122140014224180, 0x14220022140000, 0x1c141c000000, 0x14000000, 0x140000000000};
const uint64_t pos36[6] = {0x101010ef10101010, 0x8244280028448201, 0x28440044280000, 0x382838000000, 0x28000000, 0x280000000000};
const uint64_t pos37[6] = {0x202020df20202020, 0x488500050880402, 0x50880088500000, 0x705070000000, 0x50000000, 0x500000000000};
const uint64_t pos38[6] = {0x404040bf40404040, 0x810a000a0100804, 0xa0100010a00000, 0xe0a0e0000000, 0xa0000000, 0xa00000000000};
const uint64_t pos39[6] = {0x8080807f80808080, 0x1020400040201008, 0x40200020400000, 0xc040c0000000, 0x40000000, 0x400000000000};
const uint64_t pos40[6] = {0x101fe0101010101, 0x402000204081020, 0x204000402000000, 0x3020300000000, 0x200000000, 0x2000000000000};
const uint64_t pos41[6] = {0x202fd0202020202, 0x805000508102040, 0x508000805000000, 0x7050700000000, 0x500000000, 0x5000000000000};
const uint64_t pos42[6] = {0x404fb0404040404, 0x110a000a11204080, 0xa1100110a000000, 0xe0a0e00000000, 0xa00000000, 0xa000000000000};
const uint64_t pos43[6] = {0x808f70808080808, 0x2214001422418000, 0x1422002214000000, 0x1c141c00000000, 0x1400000000, 0x14000000000000};
const uint64_t pos44[6] = {0x1010ef1010101010, 0x4428002844820100, 0x2844004428000000, 0x38283800000000, 0x2800000000, 0x28000000000000};
const uint64_t pos45[6] = {0x2020df2020202020, 0x8850005088040201, 0x5088008850000000, 0x70507000000000, 0x5000000000, 0x50000000000000};
const uint64_t pos46[6] = {0x4040bf4040404040, 0x10a000a010080402, 0xa0100010a0000000, 0xe0a0e000000000, 0xa000000000, 0xa0000000000000};
const uint64_t pos47[6] = {0x80807f8080808080, 0x2040004020100804, 0x4020002040000000, 0xc040c000000000, 0x4000000000, 0x40000000000000};
const uint64_t pos48[6] = {0x1fe010101010101, 0x200020408102040, 0x400040200000000, 0x302030000000000, 0x20000000000, 0x0};
const uint64_t pos49[6] = {0x2fd020202020202, 0x500050810204080, 0x800080500000000, 0x705070000000000, 0x50000000000, 0x0};
const uint64_t pos50[6] = {0x4fb040404040404, 0xa000a1120408000, 0x1100110a00000000, 0xe0a0e0000000000, 0xa0000000000, 0x0};
const uint64_t pos51[6] = {0x8f7080808080808, 0x1400142241800000, 0x2200221400000000, 0x1c141c0000000000, 0x140000000000, 0x0};
const uint64_t pos52[6] = {0x10ef101010101010, 0x2800284482010000, 0x4400442800000000, 0x3828380000000000, 0x280000000000, 0x0};
const uint64_t pos53[6] = {0x20df202020202020, 0x5000508804020100, 0x8800885000000000, 0x7050700000000000, 0x500000000000, 0x0};
const uint64_t pos54[6] = {0x40bf404040404040, 0xa000a01008040201, 0x100010a000000000, 0xe0a0e00000000000, 0xa00000000000, 0x0};
const uint64_t pos55[6] = {0x807f808080808080, 0x4000402010080402, 0x2000204000000000, 0xc040c00000000000, 0x400000000000, 0x0};
const uint64_t pos56[6] = {0xfe01010101010101, 0x2040810204080, 0x4020000000000, 0x203000000000000, 0x2000000000000, 0x0};
const uint64_t pos57[6] = {0xfd02020202020202, 0x5081020408000, 0x8050000000000, 0x507000000000000, 0x5000000000000, 0x0};
const uint64_t pos58[6] = {0xfb04040404040404, 0xa112040800000, 0x110a0000000000, 0xa0e000000000000, 0xa000000000000, 0x0};
const uint64_t pos59[6] = {0xf708080808080808, 0x14224180000000, 0x22140000000000, 0x141c000000000000, 0x14000000000000, 0x0};
const uint64_t pos60[6] = {0xef10101010101010, 0x28448201000000, 0x44280000000000, 0x2838000000000000, 0x28000000000000, 0x0};
const uint64_t pos61[6] = {0xdf20202020202020, 0x50880402010000, 0x88500000000000, 0x5070000000000000, 0x50000000000000, 0x0};
const uint64_t pos62[6] = {0xbf40404040404040, 0xa0100804020100, 0x10a00000000000, 0xa0e0000000000000, 0xa0000000000000, 0x0};
const uint64_t pos63[6] = {0x7f80808080808080, 0x40201008040201, 0x20400000000000, 0x40c0000000000000, 0x40000000000000, 0x0};
const uint64_t *checkBitBoards[64] = {pos0, pos1, pos2, pos3, pos4, pos5, pos6, pos7, pos8, pos9, pos10, pos11, pos12, pos13, pos14, pos15, pos16, pos17, pos18, pos19, pos20, pos21, pos22, pos23, pos24, pos25, pos26, pos27, pos28, pos29, pos30, pos31, pos32, pos33, pos34, pos35, pos36, pos37, pos38, pos39, pos40, pos41, pos42, pos43, pos44, pos45, pos46, pos47, pos48, pos49, pos50, pos51, pos52, pos53, pos54, pos55, pos56, pos57, pos58, pos59, pos60, pos61, pos62, pos63};

// precomputed knight move lookup
// total length of data, position of potential move, ...
const int knightsPos0[3] = {3, 17, 10};
const int knightsPos1[4] = {4, 18, 11, 16};
const int knightsPos2[5] = {5, 19, 12, 17, 8};
const int knightsPos3[5] = {5, 20, 13, 18, 9};
const int knightsPos4[5] = {5, 21, 14, 19, 10};
const int knightsPos5[5] = {5, 22, 15, 20, 11};
const int knightsPos6[4] = {4, 23, 21, 12};
const int knightsPos7[3] = {3, 22, 13};
const int knightsPos8[4] = {4, 25, 18, 2};
const int knightsPos9[5] = {5, 26, 19, 3, 24};
const int knightsPos10[7] = {7, 27, 20, 4, 25, 16, 0};
const int knightsPos11[7] = {7, 28, 21, 5, 26, 17, 1};
const int knightsPos12[7] = {7, 29, 22, 6, 27, 18, 2};
const int knightsPos13[7] = {7, 30, 23, 7, 28, 19, 3};
const int knightsPos14[5] = {5, 31, 29, 20, 4};
const int knightsPos15[4] = {4, 30, 21, 5};
const int knightsPos16[5] = {5, 33, 26, 1, 10};
const int knightsPos17[7] = {7, 34, 27, 2, 11, 32, 0};
const int knightsPos18[9] = {9, 35, 28, 3, 12, 33, 24, 1, 8};
const int knightsPos19[9] = {9, 36, 29, 4, 13, 34, 25, 2, 9};
const int knightsPos20[9] = {9, 37, 30, 5, 14, 35, 26, 3, 10};
const int knightsPos21[9] = {9, 38, 31, 6, 15, 36, 27, 4, 11};
const int knightsPos22[7] = {7, 39, 7, 37, 28, 5, 12};
const int knightsPos23[5] = {5, 38, 29, 6, 13};
const int knightsPos24[5] = {5, 41, 34, 9, 18};
const int knightsPos25[7] = {7, 42, 35, 10, 19, 40, 8};
const int knightsPos26[9] = {9, 43, 36, 11, 20, 41, 32, 9, 16};
const int knightsPos27[9] = {9, 44, 37, 12, 21, 42, 33, 10, 17};
const int knightsPos28[9] = {9, 45, 38, 13, 22, 43, 34, 11, 18};
const int knightsPos29[9] = {9, 46, 39, 14, 23, 44, 35, 12, 19};
const int knightsPos30[7] = {7, 47, 15, 45, 36, 13, 20};
const int knightsPos31[5] = {5, 46, 37, 14, 21};
const int knightsPos32[5] = {5, 49, 42, 17, 26};
const int knightsPos33[7] = {7, 50, 43, 18, 27, 48, 16};
const int knightsPos34[9] = {9, 51, 44, 19, 28, 49, 40, 17, 24};
const int knightsPos35[9] = {9, 52, 45, 20, 29, 50, 41, 18, 25};
const int knightsPos36[9] = {9, 53, 46, 21, 30, 51, 42, 19, 26};
const int knightsPos37[9] = {9, 54, 47, 22, 31, 52, 43, 20, 27};
const int knightsPos38[7] = {7, 55, 23, 53, 44, 21, 28};
const int knightsPos39[5] = {5, 54, 45, 22, 29};
const int knightsPos40[5] = {5, 57, 50, 25, 34};
const int knightsPos41[7] = {7, 58, 51, 26, 35, 56, 24};
const int knightsPos42[9] = {9, 59, 52, 27, 36, 57, 48, 25, 32};
const int knightsPos43[9] = {9, 60, 53, 28, 37, 58, 49, 26, 33};
const int knightsPos44[9] = {9, 61, 54, 29, 38, 59, 50, 27, 34};
const int knightsPos45[9] = {9, 62, 55, 30, 39, 60, 51, 28, 35};
const int knightsPos46[7] = {7, 63, 31, 61, 52, 29, 36};
const int knightsPos47[5] = {5, 62, 53, 30, 37};
const int knightsPos48[4] = {4, 58, 33, 42};
const int knightsPos49[5] = {5, 59, 34, 43, 32};
const int knightsPos50[7] = {7, 60, 35, 44, 56, 33, 40};
const int knightsPos51[7] = {7, 61, 36, 45, 57, 34, 41};
const int knightsPos52[7] = {7, 62, 37, 46, 58, 35, 42};
const int knightsPos53[7] = {7, 63, 38, 47, 59, 36, 43};
const int knightsPos54[5] = {5, 39, 60, 37, 44};
const int knightsPos55[4] = {4, 61, 38, 45};
const int knightsPos56[3] = {3, 41, 50};
const int knightsPos57[4] = {4, 42, 51, 40};
const int knightsPos58[5] = {5, 43, 52, 41, 48};
const int knightsPos59[5] = {5, 44, 53, 42, 49};
const int knightsPos60[5] = {5, 45, 54, 43, 50};
const int knightsPos61[5] = {5, 46, 55, 44, 51};
const int knightsPos62[4] = {4, 47, 45, 52};
const int knightsPos63[3] = {3, 46, 53};
const int *knightMoves[64] = {knightsPos0, knightsPos1, knightsPos2, knightsPos3, knightsPos4, knightsPos5, knightsPos6, knightsPos7, knightsPos8, knightsPos9, knightsPos10, knightsPos11, knightsPos12, knightsPos13, knightsPos14, knightsPos15, knightsPos16, knightsPos17, knightsPos18, knightsPos19, knightsPos20, knightsPos21, knightsPos22, knightsPos23, knightsPos24, knightsPos25, knightsPos26, knightsPos27, knightsPos28, knightsPos29, knightsPos30, knightsPos31, knightsPos32, knightsPos33, knightsPos34, knightsPos35, knightsPos36, knightsPos37, knightsPos38, knightsPos39, knightsPos40, knightsPos41, knightsPos42, knightsPos43, knightsPos44, knightsPos45, knightsPos46, knightsPos47, knightsPos48, knightsPos49, knightsPos50, knightsPos51, knightsPos52, knightsPos53, knightsPos54, knightsPos55, knightsPos56, knightsPos57, knightsPos58, knightsPos59, knightsPos60, knightsPos61, knightsPos62, knightsPos63};

// precomputed king move lookup
// total length of data, position of potential move, ...
const int kingsPos0[4] = {4, 1, 8, 9};
const int kingsPos1[6] = {6, 0, 2, 8, 9, 10};
const int kingsPos2[6] = {6, 1, 3, 9, 10, 11};
const int kingsPos3[6] = {6, 2, 4, 10, 11, 12};
const int kingsPos4[6] = {6, 3, 5, 11, 12, 13};
const int kingsPos5[6] = {6, 4, 6, 12, 13, 14};
const int kingsPos6[6] = {6, 5, 7, 13, 14, 15};
const int kingsPos7[4] = {4, 6, 14, 15};
const int kingsPos8[6] = {6, 0, 1, 9, 16, 17};
const int kingsPos9[9] = {9, 0, 1, 2, 8, 10, 16, 17, 18};
const int kingsPos10[9] = {9, 1, 2, 3, 9, 11, 17, 18, 19};
const int kingsPos11[9] = {9, 2, 3, 4, 10, 12, 18, 19, 20};
const int kingsPos12[9] = {9, 3, 4, 5, 11, 13, 19, 20, 21};
const int kingsPos13[9] = {9, 4, 5, 6, 12, 14, 20, 21, 22};
const int kingsPos14[9] = {9, 5, 6, 7, 13, 15, 21, 22, 23};
const int kingsPos15[6] = {6, 6, 7, 14, 22, 23};
const int kingsPos16[6] = {6, 8, 9, 17, 24, 25};
const int kingsPos17[9] = {9, 8, 9, 10, 16, 18, 24, 25, 26};
const int kingsPos18[9] = {9, 9, 10, 11, 17, 19, 25, 26, 27};
const int kingsPos19[9] = {9, 10, 11, 12, 18, 20, 26, 27, 28};
const int kingsPos20[9] = {9, 11, 12, 13, 19, 21, 27, 28, 29};
const int kingsPos21[9] = {9, 12, 13, 14, 20, 22, 28, 29, 30};
const int kingsPos22[9] = {9, 13, 14, 15, 21, 23, 29, 30, 31};
const int kingsPos23[6] = {6, 14, 15, 22, 30, 31};
const int kingsPos24[6] = {6, 16, 17, 25, 32, 33};
const int kingsPos25[9] = {9, 16, 17, 18, 24, 26, 32, 33, 34};
const int kingsPos26[9] = {9, 17, 18, 19, 25, 27, 33, 34, 35};
const int kingsPos27[9] = {9, 18, 19, 20, 26, 28, 34, 35, 36};
const int kingsPos28[9] = {9, 19, 20, 21, 27, 29, 35, 36, 37};
const int kingsPos29[9] = {9, 20, 21, 22, 28, 30, 36, 37, 38};
const int kingsPos30[9] = {9, 21, 22, 23, 29, 31, 37, 38, 39};
const int kingsPos31[6] = {6, 22, 23, 30, 38, 39};
const int kingsPos32[6] = {6, 24, 25, 33, 40, 41};
const int kingsPos33[9] = {9, 24, 25, 26, 32, 34, 40, 41, 42};
const int kingsPos34[9] = {9, 25, 26, 27, 33, 35, 41, 42, 43};
const int kingsPos35[9] = {9, 26, 27, 28, 34, 36, 42, 43, 44};
const int kingsPos36[9] = {9, 27, 28, 29, 35, 37, 43, 44, 45};
const int kingsPos37[9] = {9, 28, 29, 30, 36, 38, 44, 45, 46};
const int kingsPos38[9] = {9, 29, 30, 31, 37, 39, 45, 46, 47};
const int kingsPos39[6] = {6, 30, 31, 38, 46, 47};
const int kingsPos40[6] = {6, 32, 33, 41, 48, 49};
const int kingsPos41[9] = {9, 32, 33, 34, 40, 42, 48, 49, 50};
const int kingsPos42[9] = {9, 33, 34, 35, 41, 43, 49, 50, 51};
const int kingsPos43[9] = {9, 34, 35, 36, 42, 44, 50, 51, 52};
const int kingsPos44[9] = {9, 35, 36, 37, 43, 45, 51, 52, 53};
const int kingsPos45[9] = {9, 36, 37, 38, 44, 46, 52, 53, 54};
const int kingsPos46[9] = {9, 37, 38, 39, 45, 47, 53, 54, 55};
const int kingsPos47[6] = {6, 38, 39, 46, 54, 55};
const int kingsPos48[6] = {6, 40, 41, 49, 56, 57};
const int kingsPos49[9] = {9, 40, 41, 42, 48, 50, 56, 57, 58};
const int kingsPos50[9] = {9, 41, 42, 43, 49, 51, 57, 58, 59};
const int kingsPos51[9] = {9, 42, 43, 44, 50, 52, 58, 59, 60};
const int kingsPos52[9] = {9, 43, 44, 45, 51, 53, 59, 60, 61};
const int kingsPos53[9] = {9, 44, 45, 46, 52, 54, 60, 61, 62};
const int kingsPos54[9] = {9, 45, 46, 47, 53, 55, 61, 62, 63};
const int kingsPos55[6] = {6, 46, 47, 54, 62, 63};
const int kingsPos56[4] = {4, 48, 49, 57};
const int kingsPos57[6] = {6, 48, 49, 50, 56, 58};
const int kingsPos58[6] = {6, 49, 50, 51, 57, 59};
const int kingsPos59[6] = {6, 50, 51, 52, 58, 60};
const int kingsPos60[6] = {6, 51, 52, 53, 59, 61};
const int kingsPos61[6] = {6, 52, 53, 54, 60, 62};
const int kingsPos62[6] = {6, 53, 54, 55, 61, 63};
const int kingsPos63[4] = {4, 54, 55, 62};
const int *kingMoves[64] = {kingsPos0, kingsPos1, kingsPos2, kingsPos3, kingsPos4, kingsPos5, kingsPos6, kingsPos7, kingsPos8, kingsPos9, kingsPos10, kingsPos11, kingsPos12, kingsPos13, kingsPos14, kingsPos15, kingsPos16, kingsPos17, kingsPos18, kingsPos19, kingsPos20, kingsPos21, kingsPos22, kingsPos23, kingsPos24, kingsPos25, kingsPos26, kingsPos27, kingsPos28, kingsPos29, kingsPos30, kingsPos31, kingsPos32, kingsPos33, kingsPos34, kingsPos35, kingsPos36, kingsPos37, kingsPos38, kingsPos39, kingsPos40, kingsPos41, kingsPos42, kingsPos43, kingsPos44, kingsPos45, kingsPos46, kingsPos47, kingsPos48, kingsPos49, kingsPos50, kingsPos51, kingsPos52, kingsPos53, kingsPos54, kingsPos55, kingsPos56, kingsPos57, kingsPos58, kingsPos59, kingsPos60, kingsPos61, kingsPos62, kingsPos63};

