#pragma once

/* warning
the move generation functions make a lot of assumptions, so custom boards with positions unreachable
in regular chess games may create bugs (ie pawns on promotion squares, opposite kings touching, etc.)
*/

#define USE_REGULAR_BOARD 1

#if USE_REGULAR_BOARD
const char startingBoard[64] = {
    blackRook, blackKnight, blackBishop, blackQueen, blackKing, blackBishop, blackKnight, blackRook,
    blackPawn, blackPawn,   blackPawn,   blackPawn,  blackPawn, blackPawn,   blackPawn,   blackPawn,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    whitePawn, whitePawn,   whitePawn,   whitePawn,  whitePawn, whitePawn,   whitePawn,   whitePawn,
    whiteRook, whiteKnight, whiteBishop, whiteQueen, whiteKing, whiteBishop, whiteKnight, whiteRook
};
#else
const char startingBoard[64] = {
    noPiece,   noPiece,     noPiece,     blackKing,    noPiece,   noPiece,     noPiece,     noPiece  ,
    blackRook,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     whiteKing,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
    noPiece,   noPiece,     noPiece,     noPiece,    noPiece,   noPiece,     noPiece,     noPiece  ,
};
#endif


// data generated by move_maker.py

// precomputed bitboards for checks
// bitmasks for: rook moves, bishop moves, knight moves, king moves, white pawn moves, black pawn moves
const uint64_t checksPos0[6] = {0x1010101010101fe, 0x8040201008040200, 0x20400, 0x302, 0x0, 0x200};
const uint64_t checksPos1[6] = {0x2020202020202fd, 0x80402010080500, 0x50800, 0x705, 0x0, 0x500};
const uint64_t checksPos2[6] = {0x4040404040404fb, 0x804020110a00, 0xa1100, 0xe0a, 0x0, 0xa00};
const uint64_t checksPos3[6] = {0x8080808080808f7, 0x8041221400, 0x142200, 0x1c14, 0x0, 0x1400};
const uint64_t checksPos4[6] = {0x10101010101010ef, 0x182442800, 0x284400, 0x3828, 0x0, 0x2800};
const uint64_t checksPos5[6] = {0x20202020202020df, 0x10204885000, 0x508800, 0x7050, 0x0, 0x5000};
const uint64_t checksPos6[6] = {0x40404040404040bf, 0x102040810a000, 0xa01000, 0xe0a0, 0x0, 0xa000};
const uint64_t checksPos7[6] = {0x808080808080807f, 0x102040810204000, 0x402000, 0xc040, 0x0, 0x4000};
const uint64_t checksPos8[6] = {0x10101010101fe01, 0x4020100804020002, 0x2040004, 0x30203, 0x0, 0x20000};
const uint64_t checksPos9[6] = {0x20202020202fd02, 0x8040201008050005, 0x5080008, 0x70507, 0x0, 0x50000};
const uint64_t checksPos10[6] = {0x40404040404fb04, 0x804020110a000a, 0xa110011, 0xe0a0e, 0x0, 0xa0000};
const uint64_t checksPos11[6] = {0x80808080808f708, 0x804122140014, 0x14220022, 0x1c141c, 0x0, 0x140000};
const uint64_t checksPos12[6] = {0x101010101010ef10, 0x18244280028, 0x28440044, 0x382838, 0x0, 0x280000};
const uint64_t checksPos13[6] = {0x202020202020df20, 0x1020488500050, 0x50880088, 0x705070, 0x0, 0x500000};
const uint64_t checksPos14[6] = {0x404040404040bf40, 0x102040810a000a0, 0xa0100010, 0xe0a0e0, 0x0, 0xa00000};
const uint64_t checksPos15[6] = {0x8080808080807f80, 0x204081020400040, 0x40200020, 0xc040c0, 0x0, 0x400000};
const uint64_t checksPos16[6] = {0x101010101fe0101, 0x2010080402000204, 0x204000402, 0x3020300, 0x0, 0x2000000};
const uint64_t checksPos17[6] = {0x202020202fd0202, 0x4020100805000508, 0x508000805, 0x7050700, 0x500, 0x5000000};
const uint64_t checksPos18[6] = {0x404040404fb0404, 0x804020110a000a11, 0xa1100110a, 0xe0a0e00, 0xa00, 0xa000000};
const uint64_t checksPos19[6] = {0x808080808f70808, 0x80412214001422, 0x1422002214, 0x1c141c00, 0x1400, 0x14000000};
const uint64_t checksPos20[6] = {0x1010101010ef1010, 0x1824428002844, 0x2844004428, 0x38283800, 0x2800, 0x28000000};
const uint64_t checksPos21[6] = {0x2020202020df2020, 0x102048850005088, 0x5088008850, 0x70507000, 0x5000, 0x50000000};
const uint64_t checksPos22[6] = {0x4040404040bf4040, 0x2040810a000a010, 0xa0100010a0, 0xe0a0e000, 0xa000, 0xa0000000};
const uint64_t checksPos23[6] = {0x80808080807f8080, 0x408102040004020, 0x4020002040, 0xc040c000, 0x4000, 0x40000000};
const uint64_t checksPos24[6] = {0x1010101fe010101, 0x1008040200020408, 0x20400040200, 0x302030000, 0x20000, 0x200000000};
const uint64_t checksPos25[6] = {0x2020202fd020202, 0x2010080500050810, 0x50800080500, 0x705070000, 0x50000, 0x500000000};
const uint64_t checksPos26[6] = {0x4040404fb040404, 0x4020110a000a1120, 0xa1100110a00, 0xe0a0e0000, 0xa0000, 0xa00000000};
const uint64_t checksPos27[6] = {0x8080808f7080808, 0x8041221400142241, 0x142200221400, 0x1c141c0000, 0x140000, 0x1400000000};
const uint64_t checksPos28[6] = {0x10101010ef101010, 0x182442800284482, 0x284400442800, 0x3828380000, 0x280000, 0x2800000000};
const uint64_t checksPos29[6] = {0x20202020df202020, 0x204885000508804, 0x508800885000, 0x7050700000, 0x500000, 0x5000000000};
const uint64_t checksPos30[6] = {0x40404040bf404040, 0x40810a000a01008, 0xa0100010a000, 0xe0a0e00000, 0xa00000, 0xa000000000};
const uint64_t checksPos31[6] = {0x808080807f808080, 0x810204000402010, 0x402000204000, 0xc040c00000, 0x400000, 0x4000000000};
const uint64_t checksPos32[6] = {0x10101fe01010101, 0x804020002040810, 0x2040004020000, 0x30203000000, 0x2000000, 0x20000000000};
const uint64_t checksPos33[6] = {0x20202fd02020202, 0x1008050005081020, 0x5080008050000, 0x70507000000, 0x5000000, 0x50000000000};
const uint64_t checksPos34[6] = {0x40404fb04040404, 0x20110a000a112040, 0xa1100110a0000, 0xe0a0e000000, 0xa000000, 0xa0000000000};
const uint64_t checksPos35[6] = {0x80808f708080808, 0x4122140014224180, 0x14220022140000, 0x1c141c000000, 0x14000000, 0x140000000000};
const uint64_t checksPos36[6] = {0x101010ef10101010, 0x8244280028448201, 0x28440044280000, 0x382838000000, 0x28000000, 0x280000000000};
const uint64_t checksPos37[6] = {0x202020df20202020, 0x488500050880402, 0x50880088500000, 0x705070000000, 0x50000000, 0x500000000000};
const uint64_t checksPos38[6] = {0x404040bf40404040, 0x810a000a0100804, 0xa0100010a00000, 0xe0a0e0000000, 0xa0000000, 0xa00000000000};
const uint64_t checksPos39[6] = {0x8080807f80808080, 0x1020400040201008, 0x40200020400000, 0xc040c0000000, 0x40000000, 0x400000000000};
const uint64_t checksPos40[6] = {0x101fe0101010101, 0x402000204081020, 0x204000402000000, 0x3020300000000, 0x200000000, 0x2000000000000};
const uint64_t checksPos41[6] = {0x202fd0202020202, 0x805000508102040, 0x508000805000000, 0x7050700000000, 0x500000000, 0x5000000000000};
const uint64_t checksPos42[6] = {0x404fb0404040404, 0x110a000a11204080, 0xa1100110a000000, 0xe0a0e00000000, 0xa00000000, 0xa000000000000};
const uint64_t checksPos43[6] = {0x808f70808080808, 0x2214001422418000, 0x1422002214000000, 0x1c141c00000000, 0x1400000000, 0x14000000000000};
const uint64_t checksPos44[6] = {0x1010ef1010101010, 0x4428002844820100, 0x2844004428000000, 0x38283800000000, 0x2800000000, 0x28000000000000};
const uint64_t checksPos45[6] = {0x2020df2020202020, 0x8850005088040201, 0x5088008850000000, 0x70507000000000, 0x5000000000, 0x50000000000000};
const uint64_t checksPos46[6] = {0x4040bf4040404040, 0x10a000a010080402, 0xa0100010a0000000, 0xe0a0e000000000, 0xa000000000, 0xa0000000000000};
const uint64_t checksPos47[6] = {0x80807f8080808080, 0x2040004020100804, 0x4020002040000000, 0xc040c000000000, 0x4000000000, 0x40000000000000};
const uint64_t checksPos48[6] = {0x1fe010101010101, 0x200020408102040, 0x400040200000000, 0x302030000000000, 0x20000000000, 0x0};
const uint64_t checksPos49[6] = {0x2fd020202020202, 0x500050810204080, 0x800080500000000, 0x705070000000000, 0x50000000000, 0x0};
const uint64_t checksPos50[6] = {0x4fb040404040404, 0xa000a1120408000, 0x1100110a00000000, 0xe0a0e0000000000, 0xa0000000000, 0x0};
const uint64_t checksPos51[6] = {0x8f7080808080808, 0x1400142241800000, 0x2200221400000000, 0x1c141c0000000000, 0x140000000000, 0x0};
const uint64_t checksPos52[6] = {0x10ef101010101010, 0x2800284482010000, 0x4400442800000000, 0x3828380000000000, 0x280000000000, 0x0};
const uint64_t checksPos53[6] = {0x20df202020202020, 0x5000508804020100, 0x8800885000000000, 0x7050700000000000, 0x500000000000, 0x0};
const uint64_t checksPos54[6] = {0x40bf404040404040, 0xa000a01008040201, 0x100010a000000000, 0xe0a0e00000000000, 0xa00000000000, 0x0};
const uint64_t checksPos55[6] = {0x807f808080808080, 0x4000402010080402, 0x2000204000000000, 0xc040c00000000000, 0x400000000000, 0x0};
const uint64_t checksPos56[6] = {0xfe01010101010101, 0x2040810204080, 0x4020000000000, 0x203000000000000, 0x2000000000000, 0x0};
const uint64_t checksPos57[6] = {0xfd02020202020202, 0x5081020408000, 0x8050000000000, 0x507000000000000, 0x5000000000000, 0x0};
const uint64_t checksPos58[6] = {0xfb04040404040404, 0xa112040800000, 0x110a0000000000, 0xa0e000000000000, 0xa000000000000, 0x0};
const uint64_t checksPos59[6] = {0xf708080808080808, 0x14224180000000, 0x22140000000000, 0x141c000000000000, 0x14000000000000, 0x0};
const uint64_t checksPos60[6] = {0xef10101010101010, 0x28448201000000, 0x44280000000000, 0x2838000000000000, 0x28000000000000, 0x0};
const uint64_t checksPos61[6] = {0xdf20202020202020, 0x50880402010000, 0x88500000000000, 0x5070000000000000, 0x50000000000000, 0x0};
const uint64_t checksPos62[6] = {0xbf40404040404040, 0xa0100804020100, 0x10a00000000000, 0xa0e0000000000000, 0xa0000000000000, 0x0};
const uint64_t checksPos63[6] = {0x7f80808080808080, 0x40201008040201, 0x20400000000000, 0x40c0000000000000, 0x40000000000000, 0x0};
const uint64_t *checkBitBoards[64] = {checksPos0, checksPos1, checksPos2, checksPos3, checksPos4, checksPos5, checksPos6, checksPos7, checksPos8, checksPos9, checksPos10, checksPos11, checksPos12, checksPos13, checksPos14, checksPos15, checksPos16, checksPos17, checksPos18, checksPos19, checksPos20, checksPos21, checksPos22, checksPos23, checksPos24, checksPos25, checksPos26, checksPos27, checksPos28, checksPos29, checksPos30, checksPos31, checksPos32, checksPos33, checksPos34, checksPos35, checksPos36, checksPos37, checksPos38, checksPos39, checksPos40, checksPos41, checksPos42, checksPos43, checksPos44, checksPos45, checksPos46, checksPos47, checksPos48, checksPos49, checksPos50, checksPos51, checksPos52, checksPos53, checksPos54, checksPos55, checksPos56, checksPos57, checksPos58, checksPos59, checksPos60, checksPos61, checksPos62, checksPos63};

const int8_t bishopsPos0[11] = {1, 2, 3, 11, 9, 18, 27, 36, 45, 54, 63};
const int8_t bishopsPos1[11] = {1, 2, 4, 8, 11, 10, 19, 28, 37, 46, 55};
const int8_t bishopsPos2[11] = {1, 2, 5, 9, 16, 11, 11, 20, 29, 38, 47};
const int8_t bishopsPos3[11] = {1, 2, 6, 10, 17, 24, 11, 12, 21, 30, 39};
const int8_t bishopsPos4[11] = {1, 2, 7, 11, 18, 25, 32, 11, 13, 22, 31};
const int8_t bishopsPos5[11] = {1, 2, 8, 12, 19, 26, 33, 40, 11, 14, 23};
const int8_t bishopsPos6[11] = {1, 2, 9, 13, 20, 27, 34, 41, 48, 11, 15};
const int8_t bishopsPos7[11] = {1, 2, 10, 14, 21, 28, 35, 42, 49, 56, 11};
const int8_t bishopsPos8[11] = {1, 3, 1, 4, 11, 17, 26, 35, 44, 53, 62};
const int8_t bishopsPos9[13] = {2, 0, 4, 2, 6, 16, 13, 18, 27, 36, 45, 54, 63};
const int8_t bishopsPos10[13] = {2, 1, 4, 3, 7, 17, 24, 13, 19, 28, 37, 46, 55};
const int8_t bishopsPos11[13] = {2, 2, 4, 4, 8, 18, 25, 32, 13, 20, 29, 38, 47};
const int8_t bishopsPos12[13] = {2, 3, 4, 5, 9, 19, 26, 33, 40, 13, 21, 30, 39};
const int8_t bishopsPos13[13] = {2, 4, 4, 6, 10, 20, 27, 34, 41, 48, 13, 22, 31};
const int8_t bishopsPos14[13] = {2, 5, 4, 7, 11, 21, 28, 35, 42, 49, 56, 13, 23};
const int8_t bishopsPos15[11] = {2, 6, 3, 10, 22, 29, 36, 43, 50, 57, 11};
const int8_t bishopsPos16[11] = {1, 4, 9, 2, 5, 11, 25, 34, 43, 52, 61};
const int8_t bishopsPos17[13] = {2, 8, 5, 10, 3, 7, 24, 13, 26, 35, 44, 53, 62};
const int8_t bishopsPos18[15] = {3, 9, 0, 6, 11, 4, 9, 25, 32, 15, 27, 36, 45, 54, 63};
const int8_t bishopsPos19[15] = {3, 10, 1, 6, 12, 5, 10, 26, 33, 40, 15, 28, 37, 46, 55};
const int8_t bishopsPos20[15] = {3, 11, 2, 6, 13, 6, 11, 27, 34, 41, 48, 15, 29, 38, 47};
const int8_t bishopsPos21[15] = {3, 12, 3, 6, 14, 7, 12, 28, 35, 42, 49, 56, 15, 30, 39};
const int8_t bishopsPos22[13] = {3, 13, 4, 5, 15, 11, 29, 36, 43, 50, 57, 13, 31};
const int8_t bishopsPos23[11] = {3, 14, 5, 4, 10, 30, 37, 44, 51, 58, 11};
const int8_t bishopsPos24[11] = {1, 5, 17, 10, 3, 6, 11, 33, 42, 51, 60};
const int8_t bishopsPos25[13] = {2, 16, 6, 18, 11, 4, 8, 32, 13, 34, 43, 52, 61};
const int8_t bishopsPos26[15] = {3, 17, 8, 7, 19, 12, 5, 10, 33, 40, 15, 35, 44, 53, 62};
const int8_t bishopsPos27[17] = {4, 18, 9, 0, 8, 20, 13, 6, 12, 34, 41, 48, 17, 36, 45, 54, 63};
const int8_t bishopsPos28[17] = {4, 19, 10, 1, 8, 21, 14, 7, 13, 35, 42, 49, 56, 17, 37, 46, 55};
const int8_t bishopsPos29[15] = {4, 20, 11, 2, 7, 22, 15, 12, 36, 43, 50, 57, 15, 38, 47};
const int8_t bishopsPos30[13] = {4, 21, 12, 3, 6, 23, 11, 37, 44, 51, 58, 13, 39};
const int8_t bishopsPos31[11] = {4, 22, 13, 4, 5, 10, 38, 45, 52, 59, 11};
const int8_t bishopsPos32[11] = {1, 6, 25, 18, 11, 4, 7, 11, 41, 50, 59};
const int8_t bishopsPos33[13] = {2, 24, 7, 26, 19, 12, 5, 9, 40, 13, 42, 51, 60};
const int8_t bishopsPos34[15] = {3, 25, 16, 8, 27, 20, 13, 6, 11, 41, 48, 15, 43, 52, 61};
const int8_t bishopsPos35[17] = {4, 26, 17, 8, 9, 28, 21, 14, 7, 13, 42, 49, 56, 17, 44, 53, 62};
const int8_t bishopsPos36[17] = {5, 27, 18, 9, 0, 9, 29, 22, 15, 13, 43, 50, 57, 17, 45, 54, 63};
const int8_t bishopsPos37[15] = {5, 28, 19, 10, 1, 8, 30, 23, 12, 44, 51, 58, 15, 46, 55};
const int8_t bishopsPos38[13] = {5, 29, 20, 11, 2, 7, 31, 11, 45, 52, 59, 13, 47};
const int8_t bishopsPos39[11] = {5, 30, 21, 12, 3, 6, 10, 46, 53, 60, 11};
const int8_t bishopsPos40[11] = {1, 7, 33, 26, 19, 12, 5, 8, 11, 49, 58};
const int8_t bishopsPos41[13] = {2, 32, 8, 34, 27, 20, 13, 6, 10, 48, 13, 50, 59};
const int8_t bishopsPos42[15] = {3, 33, 24, 9, 35, 28, 21, 14, 7, 12, 49, 56, 15, 51, 60};
const int8_t bishopsPos43[15] = {4, 34, 25, 16, 9, 36, 29, 22, 15, 12, 50, 57, 15, 52, 61};
const int8_t bishopsPos44[15] = {5, 35, 26, 17, 8, 9, 37, 30, 23, 12, 51, 58, 15, 53, 62};
const int8_t bishopsPos45[15] = {6, 36, 27, 18, 9, 0, 9, 38, 31, 12, 52, 59, 15, 54, 63};
const int8_t bishopsPos46[13] = {6, 37, 28, 19, 10, 1, 8, 39, 11, 53, 60, 13, 55};
const int8_t bishopsPos47[11] = {6, 38, 29, 20, 11, 2, 7, 10, 54, 61, 11};
const int8_t bishopsPos48[11] = {1, 8, 41, 34, 27, 20, 13, 6, 9, 11, 57};
const int8_t bishopsPos49[13] = {2, 40, 9, 42, 35, 28, 21, 14, 7, 11, 56, 13, 58};
const int8_t bishopsPos50[13] = {3, 41, 32, 9, 43, 36, 29, 22, 15, 11, 57, 13, 59};
const int8_t bishopsPos51[13] = {4, 42, 33, 24, 9, 44, 37, 30, 23, 11, 58, 13, 60};
const int8_t bishopsPos52[13] = {5, 43, 34, 25, 16, 9, 45, 38, 31, 11, 59, 13, 61};
const int8_t bishopsPos53[13] = {6, 44, 35, 26, 17, 8, 9, 46, 39, 11, 60, 13, 62};
const int8_t bishopsPos54[13] = {7, 45, 36, 27, 18, 9, 0, 9, 47, 11, 61, 13, 63};
const int8_t bishopsPos55[11] = {7, 46, 37, 28, 19, 10, 1, 8, 10, 62, 11};
const int8_t bishopsPos56[11] = {1, 9, 49, 42, 35, 28, 21, 14, 7, 10, 11};
const int8_t bishopsPos57[11] = {2, 48, 9, 50, 43, 36, 29, 22, 15, 10, 11};
const int8_t bishopsPos58[11] = {3, 49, 40, 9, 51, 44, 37, 30, 23, 10, 11};
const int8_t bishopsPos59[11] = {4, 50, 41, 32, 9, 52, 45, 38, 31, 10, 11};
const int8_t bishopsPos60[11] = {5, 51, 42, 33, 24, 9, 53, 46, 39, 10, 11};
const int8_t bishopsPos61[11] = {6, 52, 43, 34, 25, 16, 9, 54, 47, 10, 11};
const int8_t bishopsPos62[11] = {7, 53, 44, 35, 26, 17, 8, 9, 55, 10, 11};
const int8_t bishopsPos63[11] = {8, 54, 45, 36, 27, 18, 9, 0, 9, 10, 11};
const int8_t *bishopMoves[64] = {bishopsPos0, bishopsPos1, bishopsPos2, bishopsPos3, bishopsPos4, bishopsPos5, bishopsPos6, bishopsPos7, bishopsPos8, bishopsPos9, bishopsPos10, bishopsPos11, bishopsPos12, bishopsPos13, bishopsPos14, bishopsPos15, bishopsPos16, bishopsPos17, bishopsPos18, bishopsPos19, bishopsPos20, bishopsPos21, bishopsPos22, bishopsPos23, bishopsPos24, bishopsPos25, bishopsPos26, bishopsPos27, bishopsPos28, bishopsPos29, bishopsPos30, bishopsPos31, bishopsPos32, bishopsPos33, bishopsPos34, bishopsPos35, bishopsPos36, bishopsPos37, bishopsPos38, bishopsPos39, bishopsPos40, bishopsPos41, bishopsPos42, bishopsPos43, bishopsPos44, bishopsPos45, bishopsPos46, bishopsPos47, bishopsPos48, bishopsPos49, bishopsPos50, bishopsPos51, bishopsPos52, bishopsPos53, bishopsPos54, bishopsPos55, bishopsPos56, bishopsPos57, bishopsPos58, bishopsPos59, bishopsPos60, bishopsPos61, bishopsPos62, bishopsPos63};

const int8_t rooksPos0[18] = {1, 9, 1, 2, 3, 4, 5, 6, 7, 10, 18, 8, 16, 24, 32, 40, 48, 56};
const int8_t rooksPos1[18] = {1, 8, 2, 3, 4, 5, 6, 7, 10, 0, 18, 9, 17, 25, 33, 41, 49, 57};
const int8_t rooksPos2[18] = {1, 7, 3, 4, 5, 6, 7, 10, 1, 0, 18, 10, 18, 26, 34, 42, 50, 58};
const int8_t rooksPos3[18] = {1, 6, 4, 5, 6, 7, 10, 2, 1, 0, 18, 11, 19, 27, 35, 43, 51, 59};
const int8_t rooksPos4[18] = {1, 5, 5, 6, 7, 10, 3, 2, 1, 0, 18, 12, 20, 28, 36, 44, 52, 60};
const int8_t rooksPos5[18] = {1, 4, 6, 7, 10, 4, 3, 2, 1, 0, 18, 13, 21, 29, 37, 45, 53, 61};
const int8_t rooksPos6[18] = {1, 3, 7, 10, 5, 4, 3, 2, 1, 0, 18, 14, 22, 30, 38, 46, 54, 62};
const int8_t rooksPos7[18] = {1, 2, 10, 6, 5, 4, 3, 2, 1, 0, 18, 15, 23, 31, 39, 47, 55, 63};
const int8_t rooksPos8[18] = {2, 0, 10, 9, 10, 11, 12, 13, 14, 15, 11, 18, 16, 24, 32, 40, 48, 56};
const int8_t rooksPos9[18] = {2, 1, 9, 10, 11, 12, 13, 14, 15, 11, 8, 18, 17, 25, 33, 41, 49, 57};
const int8_t rooksPos10[18] = {2, 2, 8, 11, 12, 13, 14, 15, 11, 9, 8, 18, 18, 26, 34, 42, 50, 58};
const int8_t rooksPos11[18] = {2, 3, 7, 12, 13, 14, 15, 11, 10, 9, 8, 18, 19, 27, 35, 43, 51, 59};
const int8_t rooksPos12[18] = {2, 4, 6, 13, 14, 15, 11, 11, 10, 9, 8, 18, 20, 28, 36, 44, 52, 60};
const int8_t rooksPos13[18] = {2, 5, 5, 14, 15, 11, 12, 11, 10, 9, 8, 18, 21, 29, 37, 45, 53, 61};
const int8_t rooksPos14[18] = {2, 6, 4, 15, 11, 13, 12, 11, 10, 9, 8, 18, 22, 30, 38, 46, 54, 62};
const int8_t rooksPos15[18] = {2, 7, 3, 11, 14, 13, 12, 11, 10, 9, 8, 18, 23, 31, 39, 47, 55, 63};
const int8_t rooksPos16[18] = {3, 8, 0, 11, 17, 18, 19, 20, 21, 22, 23, 12, 18, 24, 32, 40, 48, 56};
const int8_t rooksPos17[18] = {3, 9, 1, 10, 18, 19, 20, 21, 22, 23, 12, 16, 18, 25, 33, 41, 49, 57};
const int8_t rooksPos18[18] = {3, 10, 2, 9, 19, 20, 21, 22, 23, 12, 17, 16, 18, 26, 34, 42, 50, 58};
const int8_t rooksPos19[18] = {3, 11, 3, 8, 20, 21, 22, 23, 12, 18, 17, 16, 18, 27, 35, 43, 51, 59};
const int8_t rooksPos20[18] = {3, 12, 4, 7, 21, 22, 23, 12, 19, 18, 17, 16, 18, 28, 36, 44, 52, 60};
const int8_t rooksPos21[18] = {3, 13, 5, 6, 22, 23, 12, 20, 19, 18, 17, 16, 18, 29, 37, 45, 53, 61};
const int8_t rooksPos22[18] = {3, 14, 6, 5, 23, 12, 21, 20, 19, 18, 17, 16, 18, 30, 38, 46, 54, 62};
const int8_t rooksPos23[18] = {3, 15, 7, 4, 12, 22, 21, 20, 19, 18, 17, 16, 18, 31, 39, 47, 55, 63};
const int8_t rooksPos24[18] = {4, 16, 8, 0, 12, 25, 26, 27, 28, 29, 30, 31, 13, 18, 32, 40, 48, 56};
const int8_t rooksPos25[18] = {4, 17, 9, 1, 11, 26, 27, 28, 29, 30, 31, 13, 24, 18, 33, 41, 49, 57};
const int8_t rooksPos26[18] = {4, 18, 10, 2, 10, 27, 28, 29, 30, 31, 13, 25, 24, 18, 34, 42, 50, 58};
const int8_t rooksPos27[18] = {4, 19, 11, 3, 9, 28, 29, 30, 31, 13, 26, 25, 24, 18, 35, 43, 51, 59};
const int8_t rooksPos28[18] = {4, 20, 12, 4, 8, 29, 30, 31, 13, 27, 26, 25, 24, 18, 36, 44, 52, 60};
const int8_t rooksPos29[18] = {4, 21, 13, 5, 7, 30, 31, 13, 28, 27, 26, 25, 24, 18, 37, 45, 53, 61};
const int8_t rooksPos30[18] = {4, 22, 14, 6, 6, 31, 13, 29, 28, 27, 26, 25, 24, 18, 38, 46, 54, 62};
const int8_t rooksPos31[18] = {4, 23, 15, 7, 5, 13, 30, 29, 28, 27, 26, 25, 24, 18, 39, 47, 55, 63};
const int8_t rooksPos32[18] = {5, 24, 16, 8, 0, 13, 33, 34, 35, 36, 37, 38, 39, 14, 18, 40, 48, 56};
const int8_t rooksPos33[18] = {5, 25, 17, 9, 1, 12, 34, 35, 36, 37, 38, 39, 14, 32, 18, 41, 49, 57};
const int8_t rooksPos34[18] = {5, 26, 18, 10, 2, 11, 35, 36, 37, 38, 39, 14, 33, 32, 18, 42, 50, 58};
const int8_t rooksPos35[18] = {5, 27, 19, 11, 3, 10, 36, 37, 38, 39, 14, 34, 33, 32, 18, 43, 51, 59};
const int8_t rooksPos36[18] = {5, 28, 20, 12, 4, 9, 37, 38, 39, 14, 35, 34, 33, 32, 18, 44, 52, 60};
const int8_t rooksPos37[18] = {5, 29, 21, 13, 5, 8, 38, 39, 14, 36, 35, 34, 33, 32, 18, 45, 53, 61};
const int8_t rooksPos38[18] = {5, 30, 22, 14, 6, 7, 39, 14, 37, 36, 35, 34, 33, 32, 18, 46, 54, 62};
const int8_t rooksPos39[18] = {5, 31, 23, 15, 7, 6, 14, 38, 37, 36, 35, 34, 33, 32, 18, 47, 55, 63};
const int8_t rooksPos40[18] = {6, 32, 24, 16, 8, 0, 14, 41, 42, 43, 44, 45, 46, 47, 15, 18, 48, 56};
const int8_t rooksPos41[18] = {6, 33, 25, 17, 9, 1, 13, 42, 43, 44, 45, 46, 47, 15, 40, 18, 49, 57};
const int8_t rooksPos42[18] = {6, 34, 26, 18, 10, 2, 12, 43, 44, 45, 46, 47, 15, 41, 40, 18, 50, 58};
const int8_t rooksPos43[18] = {6, 35, 27, 19, 11, 3, 11, 44, 45, 46, 47, 15, 42, 41, 40, 18, 51, 59};
const int8_t rooksPos44[18] = {6, 36, 28, 20, 12, 4, 10, 45, 46, 47, 15, 43, 42, 41, 40, 18, 52, 60};
const int8_t rooksPos45[18] = {6, 37, 29, 21, 13, 5, 9, 46, 47, 15, 44, 43, 42, 41, 40, 18, 53, 61};
const int8_t rooksPos46[18] = {6, 38, 30, 22, 14, 6, 8, 47, 15, 45, 44, 43, 42, 41, 40, 18, 54, 62};
const int8_t rooksPos47[18] = {6, 39, 31, 23, 15, 7, 7, 15, 46, 45, 44, 43, 42, 41, 40, 18, 55, 63};
const int8_t rooksPos48[18] = {7, 40, 32, 24, 16, 8, 0, 15, 49, 50, 51, 52, 53, 54, 55, 16, 18, 56};
const int8_t rooksPos49[18] = {7, 41, 33, 25, 17, 9, 1, 14, 50, 51, 52, 53, 54, 55, 16, 48, 18, 57};
const int8_t rooksPos50[18] = {7, 42, 34, 26, 18, 10, 2, 13, 51, 52, 53, 54, 55, 16, 49, 48, 18, 58};
const int8_t rooksPos51[18] = {7, 43, 35, 27, 19, 11, 3, 12, 52, 53, 54, 55, 16, 50, 49, 48, 18, 59};
const int8_t rooksPos52[18] = {7, 44, 36, 28, 20, 12, 4, 11, 53, 54, 55, 16, 51, 50, 49, 48, 18, 60};
const int8_t rooksPos53[18] = {7, 45, 37, 29, 21, 13, 5, 10, 54, 55, 16, 52, 51, 50, 49, 48, 18, 61};
const int8_t rooksPos54[18] = {7, 46, 38, 30, 22, 14, 6, 9, 55, 16, 53, 52, 51, 50, 49, 48, 18, 62};
const int8_t rooksPos55[18] = {7, 47, 39, 31, 23, 15, 7, 8, 16, 54, 53, 52, 51, 50, 49, 48, 18, 63};
const int8_t rooksPos56[18] = {8, 48, 40, 32, 24, 16, 8, 0, 16, 57, 58, 59, 60, 61, 62, 63, 17, 18};
const int8_t rooksPos57[18] = {8, 49, 41, 33, 25, 17, 9, 1, 15, 58, 59, 60, 61, 62, 63, 17, 56, 18};
const int8_t rooksPos58[18] = {8, 50, 42, 34, 26, 18, 10, 2, 14, 59, 60, 61, 62, 63, 17, 57, 56, 18};
const int8_t rooksPos59[18] = {8, 51, 43, 35, 27, 19, 11, 3, 13, 60, 61, 62, 63, 17, 58, 57, 56, 18};
const int8_t rooksPos60[18] = {8, 52, 44, 36, 28, 20, 12, 4, 12, 61, 62, 63, 17, 59, 58, 57, 56, 18};
const int8_t rooksPos61[18] = {8, 53, 45, 37, 29, 21, 13, 5, 11, 62, 63, 17, 60, 59, 58, 57, 56, 18};
const int8_t rooksPos62[18] = {8, 54, 46, 38, 30, 22, 14, 6, 10, 63, 17, 61, 60, 59, 58, 57, 56, 18};
const int8_t rooksPos63[18] = {8, 55, 47, 39, 31, 23, 15, 7, 9, 17, 62, 61, 60, 59, 58, 57, 56, 18};
const int8_t *rookMoves[64] = {rooksPos0, rooksPos1, rooksPos2, rooksPos3, rooksPos4, rooksPos5, rooksPos6, rooksPos7, rooksPos8, rooksPos9, rooksPos10, rooksPos11, rooksPos12, rooksPos13, rooksPos14, rooksPos15, rooksPos16, rooksPos17, rooksPos18, rooksPos19, rooksPos20, rooksPos21, rooksPos22, rooksPos23, rooksPos24, rooksPos25, rooksPos26, rooksPos27, rooksPos28, rooksPos29, rooksPos30, rooksPos31, rooksPos32, rooksPos33, rooksPos34, rooksPos35, rooksPos36, rooksPos37, rooksPos38, rooksPos39, rooksPos40, rooksPos41, rooksPos42, rooksPos43, rooksPos44, rooksPos45, rooksPos46, rooksPos47, rooksPos48, rooksPos49, rooksPos50, rooksPos51, rooksPos52, rooksPos53, rooksPos54, rooksPos55, rooksPos56, rooksPos57, rooksPos58, rooksPos59, rooksPos60, rooksPos61, rooksPos62, rooksPos63};

const int8_t knightsPos0[3] = {3, 17, 10};
const int8_t knightsPos1[4] = {4, 18, 11, 16};
const int8_t knightsPos2[5] = {5, 19, 12, 17, 8};
const int8_t knightsPos3[5] = {5, 20, 13, 18, 9};
const int8_t knightsPos4[5] = {5, 21, 14, 19, 10};
const int8_t knightsPos5[5] = {5, 22, 15, 20, 11};
const int8_t knightsPos6[4] = {4, 23, 21, 12};
const int8_t knightsPos7[3] = {3, 22, 13};
const int8_t knightsPos8[4] = {4, 25, 18, 2};
const int8_t knightsPos9[5] = {5, 26, 19, 3, 24};
const int8_t knightsPos10[7] = {7, 27, 20, 4, 25, 16, 0};
const int8_t knightsPos11[7] = {7, 28, 21, 5, 26, 17, 1};
const int8_t knightsPos12[7] = {7, 29, 22, 6, 27, 18, 2};
const int8_t knightsPos13[7] = {7, 30, 23, 7, 28, 19, 3};
const int8_t knightsPos14[5] = {5, 31, 29, 20, 4};
const int8_t knightsPos15[4] = {4, 30, 21, 5};
const int8_t knightsPos16[5] = {5, 33, 26, 1, 10};
const int8_t knightsPos17[7] = {7, 34, 27, 2, 11, 32, 0};
const int8_t knightsPos18[9] = {9, 35, 28, 3, 12, 33, 24, 1, 8};
const int8_t knightsPos19[9] = {9, 36, 29, 4, 13, 34, 25, 2, 9};
const int8_t knightsPos20[9] = {9, 37, 30, 5, 14, 35, 26, 3, 10};
const int8_t knightsPos21[9] = {9, 38, 31, 6, 15, 36, 27, 4, 11};
const int8_t knightsPos22[7] = {7, 39, 7, 37, 28, 5, 12};
const int8_t knightsPos23[5] = {5, 38, 29, 6, 13};
const int8_t knightsPos24[5] = {5, 41, 34, 9, 18};
const int8_t knightsPos25[7] = {7, 42, 35, 10, 19, 40, 8};
const int8_t knightsPos26[9] = {9, 43, 36, 11, 20, 41, 32, 9, 16};
const int8_t knightsPos27[9] = {9, 44, 37, 12, 21, 42, 33, 10, 17};
const int8_t knightsPos28[9] = {9, 45, 38, 13, 22, 43, 34, 11, 18};
const int8_t knightsPos29[9] = {9, 46, 39, 14, 23, 44, 35, 12, 19};
const int8_t knightsPos30[7] = {7, 47, 15, 45, 36, 13, 20};
const int8_t knightsPos31[5] = {5, 46, 37, 14, 21};
const int8_t knightsPos32[5] = {5, 49, 42, 17, 26};
const int8_t knightsPos33[7] = {7, 50, 43, 18, 27, 48, 16};
const int8_t knightsPos34[9] = {9, 51, 44, 19, 28, 49, 40, 17, 24};
const int8_t knightsPos35[9] = {9, 52, 45, 20, 29, 50, 41, 18, 25};
const int8_t knightsPos36[9] = {9, 53, 46, 21, 30, 51, 42, 19, 26};
const int8_t knightsPos37[9] = {9, 54, 47, 22, 31, 52, 43, 20, 27};
const int8_t knightsPos38[7] = {7, 55, 23, 53, 44, 21, 28};
const int8_t knightsPos39[5] = {5, 54, 45, 22, 29};
const int8_t knightsPos40[5] = {5, 57, 50, 25, 34};
const int8_t knightsPos41[7] = {7, 58, 51, 26, 35, 56, 24};
const int8_t knightsPos42[9] = {9, 59, 52, 27, 36, 57, 48, 25, 32};
const int8_t knightsPos43[9] = {9, 60, 53, 28, 37, 58, 49, 26, 33};
const int8_t knightsPos44[9] = {9, 61, 54, 29, 38, 59, 50, 27, 34};
const int8_t knightsPos45[9] = {9, 62, 55, 30, 39, 60, 51, 28, 35};
const int8_t knightsPos46[7] = {7, 63, 31, 61, 52, 29, 36};
const int8_t knightsPos47[5] = {5, 62, 53, 30, 37};
const int8_t knightsPos48[4] = {4, 58, 33, 42};
const int8_t knightsPos49[5] = {5, 59, 34, 43, 32};
const int8_t knightsPos50[7] = {7, 60, 35, 44, 56, 33, 40};
const int8_t knightsPos51[7] = {7, 61, 36, 45, 57, 34, 41};
const int8_t knightsPos52[7] = {7, 62, 37, 46, 58, 35, 42};
const int8_t knightsPos53[7] = {7, 63, 38, 47, 59, 36, 43};
const int8_t knightsPos54[5] = {5, 39, 60, 37, 44};
const int8_t knightsPos55[4] = {4, 61, 38, 45};
const int8_t knightsPos56[3] = {3, 41, 50};
const int8_t knightsPos57[4] = {4, 42, 51, 40};
const int8_t knightsPos58[5] = {5, 43, 52, 41, 48};
const int8_t knightsPos59[5] = {5, 44, 53, 42, 49};
const int8_t knightsPos60[5] = {5, 45, 54, 43, 50};
const int8_t knightsPos61[5] = {5, 46, 55, 44, 51};
const int8_t knightsPos62[4] = {4, 47, 45, 52};
const int8_t knightsPos63[3] = {3, 46, 53};
const int8_t *knightMoves[64] = {knightsPos0, knightsPos1, knightsPos2, knightsPos3, knightsPos4, knightsPos5, knightsPos6, knightsPos7, knightsPos8, knightsPos9, knightsPos10, knightsPos11, knightsPos12, knightsPos13, knightsPos14, knightsPos15, knightsPos16, knightsPos17, knightsPos18, knightsPos19, knightsPos20, knightsPos21, knightsPos22, knightsPos23, knightsPos24, knightsPos25, knightsPos26, knightsPos27, knightsPos28, knightsPos29, knightsPos30, knightsPos31, knightsPos32, knightsPos33, knightsPos34, knightsPos35, knightsPos36, knightsPos37, knightsPos38, knightsPos39, knightsPos40, knightsPos41, knightsPos42, knightsPos43, knightsPos44, knightsPos45, knightsPos46, knightsPos47, knightsPos48, knightsPos49, knightsPos50, knightsPos51, knightsPos52, knightsPos53, knightsPos54, knightsPos55, knightsPos56, knightsPos57, knightsPos58, knightsPos59, knightsPos60, knightsPos61, knightsPos62, knightsPos63};

const int8_t kingsPos0[4] = {4, 1, 8, 9};
const int8_t kingsPos1[6] = {6, 0, 2, 8, 9, 10};
const int8_t kingsPos2[6] = {6, 1, 3, 9, 10, 11};
const int8_t kingsPos3[6] = {6, 2, 4, 10, 11, 12};
const int8_t kingsPos4[6] = {6, 3, 5, 11, 12, 13};
const int8_t kingsPos5[6] = {6, 4, 6, 12, 13, 14};
const int8_t kingsPos6[6] = {6, 5, 7, 13, 14, 15};
const int8_t kingsPos7[4] = {4, 6, 14, 15};
const int8_t kingsPos8[6] = {6, 0, 1, 9, 16, 17};
const int8_t kingsPos9[9] = {9, 0, 1, 2, 8, 10, 16, 17, 18};
const int8_t kingsPos10[9] = {9, 1, 2, 3, 9, 11, 17, 18, 19};
const int8_t kingsPos11[9] = {9, 2, 3, 4, 10, 12, 18, 19, 20};
const int8_t kingsPos12[9] = {9, 3, 4, 5, 11, 13, 19, 20, 21};
const int8_t kingsPos13[9] = {9, 4, 5, 6, 12, 14, 20, 21, 22};
const int8_t kingsPos14[9] = {9, 5, 6, 7, 13, 15, 21, 22, 23};
const int8_t kingsPos15[6] = {6, 6, 7, 14, 22, 23};
const int8_t kingsPos16[6] = {6, 8, 9, 17, 24, 25};
const int8_t kingsPos17[9] = {9, 8, 9, 10, 16, 18, 24, 25, 26};
const int8_t kingsPos18[9] = {9, 9, 10, 11, 17, 19, 25, 26, 27};
const int8_t kingsPos19[9] = {9, 10, 11, 12, 18, 20, 26, 27, 28};
const int8_t kingsPos20[9] = {9, 11, 12, 13, 19, 21, 27, 28, 29};
const int8_t kingsPos21[9] = {9, 12, 13, 14, 20, 22, 28, 29, 30};
const int8_t kingsPos22[9] = {9, 13, 14, 15, 21, 23, 29, 30, 31};
const int8_t kingsPos23[6] = {6, 14, 15, 22, 30, 31};
const int8_t kingsPos24[6] = {6, 16, 17, 25, 32, 33};
const int8_t kingsPos25[9] = {9, 16, 17, 18, 24, 26, 32, 33, 34};
const int8_t kingsPos26[9] = {9, 17, 18, 19, 25, 27, 33, 34, 35};
const int8_t kingsPos27[9] = {9, 18, 19, 20, 26, 28, 34, 35, 36};
const int8_t kingsPos28[9] = {9, 19, 20, 21, 27, 29, 35, 36, 37};
const int8_t kingsPos29[9] = {9, 20, 21, 22, 28, 30, 36, 37, 38};
const int8_t kingsPos30[9] = {9, 21, 22, 23, 29, 31, 37, 38, 39};
const int8_t kingsPos31[6] = {6, 22, 23, 30, 38, 39};
const int8_t kingsPos32[6] = {6, 24, 25, 33, 40, 41};
const int8_t kingsPos33[9] = {9, 24, 25, 26, 32, 34, 40, 41, 42};
const int8_t kingsPos34[9] = {9, 25, 26, 27, 33, 35, 41, 42, 43};
const int8_t kingsPos35[9] = {9, 26, 27, 28, 34, 36, 42, 43, 44};
const int8_t kingsPos36[9] = {9, 27, 28, 29, 35, 37, 43, 44, 45};
const int8_t kingsPos37[9] = {9, 28, 29, 30, 36, 38, 44, 45, 46};
const int8_t kingsPos38[9] = {9, 29, 30, 31, 37, 39, 45, 46, 47};
const int8_t kingsPos39[6] = {6, 30, 31, 38, 46, 47};
const int8_t kingsPos40[6] = {6, 32, 33, 41, 48, 49};
const int8_t kingsPos41[9] = {9, 32, 33, 34, 40, 42, 48, 49, 50};
const int8_t kingsPos42[9] = {9, 33, 34, 35, 41, 43, 49, 50, 51};
const int8_t kingsPos43[9] = {9, 34, 35, 36, 42, 44, 50, 51, 52};
const int8_t kingsPos44[9] = {9, 35, 36, 37, 43, 45, 51, 52, 53};
const int8_t kingsPos45[9] = {9, 36, 37, 38, 44, 46, 52, 53, 54};
const int8_t kingsPos46[9] = {9, 37, 38, 39, 45, 47, 53, 54, 55};
const int8_t kingsPos47[6] = {6, 38, 39, 46, 54, 55};
const int8_t kingsPos48[6] = {6, 40, 41, 49, 56, 57};
const int8_t kingsPos49[9] = {9, 40, 41, 42, 48, 50, 56, 57, 58};
const int8_t kingsPos50[9] = {9, 41, 42, 43, 49, 51, 57, 58, 59};
const int8_t kingsPos51[9] = {9, 42, 43, 44, 50, 52, 58, 59, 60};
const int8_t kingsPos52[9] = {9, 43, 44, 45, 51, 53, 59, 60, 61};
const int8_t kingsPos53[9] = {9, 44, 45, 46, 52, 54, 60, 61, 62};
const int8_t kingsPos54[9] = {9, 45, 46, 47, 53, 55, 61, 62, 63};
const int8_t kingsPos55[6] = {6, 46, 47, 54, 62, 63};
const int8_t kingsPos56[4] = {4, 48, 49, 57};
const int8_t kingsPos57[6] = {6, 48, 49, 50, 56, 58};
const int8_t kingsPos58[6] = {6, 49, 50, 51, 57, 59};
const int8_t kingsPos59[6] = {6, 50, 51, 52, 58, 60};
const int8_t kingsPos60[6] = {6, 51, 52, 53, 59, 61};
const int8_t kingsPos61[6] = {6, 52, 53, 54, 60, 62};
const int8_t kingsPos62[6] = {6, 53, 54, 55, 61, 63};
const int8_t kingsPos63[4] = {4, 54, 55, 62};
const int8_t *kingMoves[64] = {kingsPos0, kingsPos1, kingsPos2, kingsPos3, kingsPos4, kingsPos5, kingsPos6, kingsPos7, kingsPos8, kingsPos9, kingsPos10, kingsPos11, kingsPos12, kingsPos13, kingsPos14, kingsPos15, kingsPos16, kingsPos17, kingsPos18, kingsPos19, kingsPos20, kingsPos21, kingsPos22, kingsPos23, kingsPos24, kingsPos25, kingsPos26, kingsPos27, kingsPos28, kingsPos29, kingsPos30, kingsPos31, kingsPos32, kingsPos33, kingsPos34, kingsPos35, kingsPos36, kingsPos37, kingsPos38, kingsPos39, kingsPos40, kingsPos41, kingsPos42, kingsPos43, kingsPos44, kingsPos45, kingsPos46, kingsPos47, kingsPos48, kingsPos49, kingsPos50, kingsPos51, kingsPos52, kingsPos53, kingsPos54, kingsPos55, kingsPos56, kingsPos57, kingsPos58, kingsPos59, kingsPos60, kingsPos61, kingsPos62, kingsPos63};